 const ProductData = [
    {
      id: "2173",
      title: "Apollo AMAZER 4G LIFE 145/80 R12 74T TT",
      price: "₹ 3,247",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-145-ar-80-rs-12",
      name: "AMAZER 4G LIFE",
      size: "145/80 R12",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tube Type",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "2174",
      title: "Apollo AMAZER 4G LIFE 145/80 R13 75 T TL",
      price: "₹ 3,556",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-145-ar-80-rs-13",
      name: "AMAZER 4G LIFE",
      size: "145/80 R13",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "2175",
      title: "Apollo AMAZER 4G LIFE 155/65 R13 73 T TL",
      price: "₹ 3,786",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-155-ar-65-rs-13",
      name: "AMAZER 4G LIFE",
      size: "155/65 R13",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "2177",
      title: "Apollo AMAZER 4G LIFE 155/70 R13 75 T TL",
      price: "₹ 3,873",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-155-ar-70-rs-13",
      name: "AMAZER 4G LIFE",
      size: "155/70 R13",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "5304",
      title: "Apollo AMAZER 4G LIFE 165/70 R14 81T TL",
      price: "₹ 3,952",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-70-rs-14",
      name: "AMAZER 4G LIFE",
      size: "165/70 R14",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "2178",
      title: "Apollo AMAZER 4G LIFE 165/70 R13 79 T TL",
      price: "₹ 4,013",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-70-rs-13",
      name: "AMAZER 4G LIFE",
      size: "165/70 R13",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "2180",
      title: "Apollo AMAZER 4G LIFE 155/65 R14 75 T TL",
      price: "₹ 4,074",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-155-ar-65-rs-14",
      name: "AMAZER 4G LIFE",
      size: "155/65 R14",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://sp-ao.shortpixel.ai/client/q_lossless,ret_img,w_1200/https://www.tyremarket.com/tyremantra/wp-content/uploads/2016/08/apollo_tyres_logo-Cropped-1200x675.jpg",
        name: "Apollo",
        value:"apollo",
      },
    },
    {
      id: "2176",
      title: "MRF 165/65 R13 77 T TL",
      price: "₹ 4,090",
      imageUrl:
        "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
      link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
      name: "AMAZER 4G LIFE",
      size: "165/65 R13",
      rating: 4,
      reviews: "320 Reviews",
      feature: "Tubeless",
      warranty: "5 Year Warranty",
      BrandsData:{
        href: "//www.tyreplex.com/mrf-tyres",
        logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
        name: "MRF",
        value:"mrf",
      },
    },
    {
        id: "2200",
        title: "MRF 165/65 R13 77 T TL",
        price: "₹ 4,090",
        imageUrl:
          "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
        link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
        name: "AMAZER 4G LIFE",
        size: "165/65 R13",
        rating: 4,
        reviews: "320 Reviews",
        feature: "Tubeless",
        warranty: "5 Year Warranty",
        BrandsData:{
          href: "//www.tyreplex.com/mrf-tyres",
          logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
          name: "MRF",
          value:"mrf",
        },
      },
      {
        id: "2201",
        title: "MRF 165/65 R13 77 T TL",
        price: "₹ 4,090",
        imageUrl:
          "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
        link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
        name: "AMAZER 4G LIFE",
        size: "165/65 R13",
        rating: 4,
        reviews: "320 Reviews",
        feature: "Tubeless",
        warranty: "5 Year Warranty",BrandsData:{
          href: "//www.tyreplex.com/mrf-tyres",
          logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
          name: "MRF",
          value:"mrf",
        },
      },
      {
        id: "2202",
        title: "MRF 165/65 R13 77 T TL",
        price: "₹ 4,090",
        imageUrl:
          "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
        link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
        name: "AMAZER 4G LIFE",
        size: "165/65 R13",
        rating: 4,
        reviews: "320 Reviews",
        feature: "Tubeless",
        warranty: "5 Year Warranty",BrandsData:{
          href: "//www.tyreplex.com/mrf-tyres",
          logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
          name: "MRF",
          value:"mrf",
        },
      },
      {
        id: "2203",
        title: "MRF 165/65 R13 77 T TL",
        price: "₹ 4,090",
        imageUrl:
          "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
        link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
        name: "AMAZER 4G LIFE",
        size: "165/65 R13",
        rating: 4,
        reviews: "320 Reviews",
        feature: "Tubeless",
        warranty: "5 Year Warranty",BrandsData:{
          href: "//www.tyreplex.com/mrf-tyres",
          logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
          name: "MRF",
          value:"mrf",
        },
      },
      {
        id: "2204",
        title: "MRF 165/65 R13 77 T TL",
        price: "₹ 4,090",
        imageUrl:
          "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
        link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
        name: "AMAZER 4G LIFE",
        size: "165/65 R13",
        rating: 4,
        reviews: "320 Reviews",
        feature: "Tubeless",
        warranty: "5 Year Warranty",
        BrandsData:{
          href: "//www.tyreplex.com/mrf-tyres",
          logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
          name: "MRF",
          value:"mrf",
        },
      },
      {
        id: "2205",
        title: "MRF 165/65 R13 77 T TL",
        price: "₹ 4,090",
        imageUrl:
          "https://cdn.tyreplex.net/uploads/images/tyre_model/original/apollo/amazer-4g-life/img_main.png?v=2385909&tr=w-250,q-60",
        link: "//www.tyreplex.com/apollo-tyres/amazer-4g-life/sw-165-ar-65-rs-13",
        name: "AMAZER 4G LIFE",
        size: "165/65 R13",
        rating: 4,
        reviews: "320 Reviews",
        feature: "Tubeless",
        warranty: "5 Year Warranty",
        BrandsData:{
          href: "//www.tyreplex.com/mrf-tyres",
          logoClass: "https://1000logos.net/wp-content/uploads/2022/12/MRF-Logo.png",
          name: "MRF",
          value:"mrf",
        },
      },
  ];
  export default ProductData